"""Runbook templates for Remediator findings."""

from __future__ import annotations

from chaos_agent.remediator.models import RemediationFinding


def render_runbook(finding: RemediationFinding) -> str:
    evidence = "\n".join(f"- {e}" for e in finding.evidence)
    return f"""# Runbook: {finding.title}

**Severity:** {finding.severity.value}  
**Scope:** {finding.scope}  
**Experiment:** `{finding.experiment_id or 'n/a'}`

## Symptoms / Evidence
{evidence}

## Prescription
{finding.prescription}

## Remediation steps
1. Review suggested change in `{finding.target_path or 'repo'}`.
2. Apply patch (see diff below).
3. Deploy to staging.
4. Re-run chaos experiment to verify.

## Suggested change
```
{finding.suggested_diff or '# No diff generated'}
```

## Verification
{finding.verification or 'Re-run source experiment; steady-state guard should not breach.'}

---
_Auto-generated by Chaos Agent Remediator._
"""
