export const queryKeys = {
  health: ['health'] as const,
  dashboard: (namespace: string) => ['dashboard', 'stats', namespace] as const,
  experiments: (namespace: string) => ['experiments', namespace] as const,
  contextTargets: ['context', 'targets'] as const,
  experiment: (id: string) => ['experiments', id] as const,
  experimentEvidence: (id: string) => ['observability', 'evidence', id] as const,
  observabilityStatus: ['observability', 'status'] as const,
  observabilityCatalog: ['observability', 'catalog'] as const,
  posture: (namespace: string) => ['posture', namespace] as const,
  snapshot: (namespace: string) => ['snapshot', namespace] as const,
  campaigns: ['red-blue', 'campaigns'] as const,
  campaign: (id: string) => ['red-blue', 'campaigns', id] as const,
  contextSnapshot: (namespace: string) => ['context', 'snapshot', namespace] as const,
  contextAnalysis: (namespace: string) => ['context', 'analysis', namespace] as const,
  attackFrameworks: ['red-blue', 'frameworks'] as const,
  remediationFindings: ['remediation', 'findings'] as const,
  experimentRemediation: (id: string) => ['remediation', 'experiments', id] as const,
  agentStatus: ['agents', 'status'] as const,
  infrastructure: (namespace: string) => ['platform', 'infrastructure', namespace] as const,
  twin: (namespace: string, target: string) => ['platform', 'twin', namespace, target] as const,
  policyRuntime: ['policies', 'runtime'] as const,
  policyRules: ['policies', 'posture-rules'] as const,
  policyYaml: ['policies', 'yaml'] as const,
  integrations: ['integrations'] as const,
  chaosDna: (namespace: string) => ['chaos-dna', namespace] as const,
  loadTests: ['load-tests'] as const,
  refereeScoring: ['referee', 'scoring'] as const,
  refereeFreeze: ['referee', 'freeze'] as const,
  regression: ['regression'] as const,
}
