"""Blue remediation — GitHub PR and closed-loop verify."""

from __future__ import annotations

from typing import Any

from chaos_agent.integrations.github.client import GitHubClient
from chaos_agent.red_blue.experiments import inject_attack
from chaos_agent.security.scanners.dast import run_dast_probe
from chaos_agent.security.types import BlueDefense, RedAttack, SecurityAttackSpec


async def open_blue_pr(defense: BlueDefense) -> dict[str, Any]:
    client = GitHubClient()
    title = f"[Blue] {defense.title}"
    body = (
        f"## Chaos Agent — Blue remediation\n\n"
        f"**Action:** {defense.action}\n\n"
        f"**Target:** `{defense.target_path}`\n\n"
        f"**Artifact:** {defense.artifact_type}\n\n"
        f"```diff\n{defense.suggested_diff}\n```\n\n"
        f"_Auto-generated by Blue agent. Review before merge._"
    )
    branch = f"blue/{defense.attack_id}"
    return await client.create_pull_request(
        title=title,
        body=body,
        branch=branch,
        file_path=defense.target_path,
        file_content=defense.suggested_diff,
    )


async def verify_round(attack: RedAttack, defense: BlueDefense) -> dict[str, Any]:
    return await verify_round_full(attack, defense, re_inject=False)


async def verify_round_full(
    attack: RedAttack,
    defense: BlueDefense,
    *,
    namespace: str = "staging",
    re_inject: bool = True,
) -> dict[str, Any]:
    results: dict[str, Any] = {
        "probe": attack.technique,
        "defense": defense.title,
        "checks": [],
    }

    spec = SecurityAttackSpec(
        id=attack.id,
        name=attack.title,
        category=attack.category,
        technique=attack.technique,
        target_service=attack.service,
        description=attack.description,
        cwe=attack.cwe,
        severity_if_success="high",
    )
    dast = await run_dast_probe(spec)
    results["checks"].append({"type": "dast", "passed": dast.passed, "message": dast.message})

    inject_result = None
    if re_inject:
        inject_result = await inject_attack(attack, namespace)
        results["checks"].append(
            {
                "type": "re_inject",
                "passed": inject_result.get("injected") and not inject_result.get("slo_breached"),
                "experiment_id": inject_result.get("experiment_id"),
                "slo_breached": inject_result.get("slo_breached"),
            },
        )

    verified = all(c["passed"] for c in results["checks"])
    results["verified"] = verified
    results["simulated"] = dast.simulated
    results["message"] = "Defense verified" if verified else "Verification failed — see checks"
    if inject_result:
        results["inject_result"] = inject_result
    return results
